# Generated by Django 5.0.3 on 2024-07-10 13:59

import django.core.validators
import project.fields.flowbite
import project.models
import project.storage_backends
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', project.fields.flowbite.ModelCharField(help_text='Name of the room', max_length=50, unique=True, verbose_name='Name')),
                ('location', project.fields.flowbite.ModelCharField(blank=True, default='', help_text='Room location', max_length=50, verbose_name='Location')),
                ('price', project.fields.flowbite.ModelFloatField(default=0, help_text='Price per hour of the room', verbose_name='Hourly price')),
                ('capacity', project.fields.flowbite.ModelIntegerField(default=0, help_text='Maximum seating capacity of the room', verbose_name='Capacity')),
                ('picture', project.fields.flowbite.ModelImageField(blank=True, help_text='Photo of the room', null=True, storage=project.storage_backends.PublicMediaStorage(), upload_to='', validators=[django.core.validators.validate_image_file_extension], verbose_name='Picture')),
                ('equipment', project.fields.flowbite.ModelCharField(blank=True, default='', help_text='Available equipment in the room', max_length=500, verbose_name='Equipment')),
                ('room_type', project.fields.flowbite.ModelCharField(choices=[('event_room', 'Event Room')], help_text='Room type', max_length=50, verbose_name='Room type')),
            ],
            options={
                'verbose_name': 'room',
                'verbose_name_plural': 'rooms',
                'ordering': ['name'],
            },
            bases=(project.models.SetBooleanDatetimeMixin, models.Model),
        ),
    ]
