# Generated by Django 5.0.3 on 2024-09-17 11:40

import django.core.validators
import project.models
import project.storage_backends
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(default='', help_text='Name of the room', max_length=50, unique=True, verbose_name='Name')),
                ('code', models.CharField(blank=True, default='', max_length=50, verbose_name='Room code')),
                ('price', models.FloatField(default=0, help_text='Price per hour of the room', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Hourly price')),
                ('price_half_day', models.FloatField(default=0, help_text='Price per half day of the room', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Half day price')),
                ('price_all_day', models.FloatField(default=0, help_text='Price per all day of the room', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='All day price')),
                ('capacity', models.IntegerField(default=0, help_text='Maximum seating capacity of the room', verbose_name='Capacity')),
                ('picture', models.ImageField(default='', help_text='Photo of the room', storage=project.storage_backends.PrivateMediaStorage(), upload_to='', validators=[django.core.validators.validate_image_file_extension], verbose_name='Picture')),
                ('equipment', models.CharField(blank=True, default='', help_text='Available equipment in the room', max_length=500, verbose_name='Equipment')),
                ('description', models.CharField(default='', help_text='Description of the main aspects of the room.', max_length=500, verbose_name='Description')),
                ('room_type', models.CharField(choices=[('event_room', 'Event Room'), ('classroom', 'Classroom'), ('meeting_room', 'Meeting room')], help_text='Room type', max_length=50, verbose_name='Room type')),
            ],
            options={
                'verbose_name': 'room',
                'verbose_name_plural': 'rooms',
                'ordering': ['name'],
            },
            bases=(project.models.SetBooleanDatetimeMixin, models.Model),
        ),
    ]
