# Generated by Django 5.0.3 on 2024-09-12 14:23

import django.core.validators
import project.fields.flowbite
import project.storage_backends
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='location',
        ),
        migrations.AddField(
            model_name='room',
            name='code',
            field=project.fields.flowbite.ModelCharField(blank=True, default='', max_length=50, verbose_name='Room code'),
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=project.fields.flowbite.ModelCharField(default='', help_text='Description of the main aspects of the room.', max_length=500, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='room',
            name='price_all_day',
            field=project.fields.flowbite.ModelFloatField(default=0, help_text='Price per all day of the room', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='All day price'),
        ),
        migrations.AddField(
            model_name='room',
            name='price_half_day',
            field=project.fields.flowbite.ModelFloatField(default=0, help_text='Price per half day of the room', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Half day price'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=project.fields.flowbite.ModelCharField(default='', help_text='Name of the room', max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='room',
            name='picture',
            field=project.fields.flowbite.ModelImageField(default='', help_text='Photo of the room', storage=project.storage_backends.PublicMediaStorage(), upload_to='', validators=[django.core.validators.validate_image_file_extension], verbose_name='Picture'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=project.fields.flowbite.ModelFloatField(default=0, help_text='Price per hour of the room', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Hourly price'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=project.fields.flowbite.ModelCharField(choices=[('event_room', 'Event Room'), ('classroom', 'Classroom'), ('meeting_room', 'Meeting room')], help_text='Room type', max_length=50, verbose_name='Room type'),
        ),
    ]
