# Generated by Django 5.0.3 on 2024-11-27 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('event_room', 'Event Room'), ('classroom', 'Classroom'), ('meeting_room', 'Meeting room')], max_length=50, verbose_name='Room type'),
        ),
    ]
