# Generated by Django 5.0.3 on 2024-08-26 11:50

import django.core.validators
import project.fields.flowbite
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price_all_day',
            field=project.fields.flowbite.ModelFloatField(default=0, help_text='Price per all day of the room', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='All day price'),
        ),
        migrations.AddField(
            model_name='room',
            name='price_half_day',
            field=project.fields.flowbite.ModelFloatField(default=0, help_text='Price per half day of the room', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Half day price'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=project.fields.flowbite.ModelFloatField(default=0, help_text='Price per hour of the room', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Hourly price'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=project.fields.flowbite.ModelCharField(choices=[('event_room', 'Event Room'), ('classroom', 'Classroom'), ('meeting_room', 'Meeting room')], help_text='Room type', max_length=50, verbose_name='Room type'),
        ),
    ]
