# Generated by Django 5.0.3 on 2024-09-16 14:07

import django.core.validators
import project.fields.flowbite
import project.storage_backends
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_remove_room_location_room_code_room_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='picture',
            field=project.fields.flowbite.ModelImageField(default='', help_text='Photo of the room', storage=project.storage_backends.PrivateMediaStorage(), upload_to='', validators=[django.core.validators.validate_image_file_extension], verbose_name='Picture'),
        ),
    ]
