# Generated by Django 5.0.3 on 2025-03-21 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_room_description_alter_room_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Hourly price (VAT not included)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_all_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='All day price (VAT not included)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_half_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Half day price (VAT not included)'),
        ),
    ]
