# Generated by Django 5.0.3 on 2024-08-29 08:11

import project.fields.flowbite
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_price_all_day_room_price_half_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='description',
            field=project.fields.flowbite.ModelCharField(default='', help_text='Description of the main aspects of the room.', max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=project.fields.flowbite.ModelCharField(default='', help_text='Name of the room', max_length=50, unique=True, verbose_name='Name'),
        ),
    ]
