# Generated by Django 5.0.3 on 2024-08-30 14:33

import django.core.validators
import project.fields.flowbite
import project.storage_backends
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_room_description_alter_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='picture',
            field=project.fields.flowbite.ModelImageField(help_text='Photo of the room', storage=project.storage_backends.PublicMediaStorage(), upload_to='', validators=[django.core.validators.validate_image_file_extension], verbose_name='Picture'),
        ),
    ]
