# Generated by Django 5.0.3 on 2024-09-02 15:00

import project.fields.flowbite
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_alter_room_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='location',
        ),
        migrations.AddField(
            model_name='room',
            name='code',
            field=project.fields.flowbite.ModelCharField(blank=True, default='', max_length=50, verbose_name='Room code'),
        ),
    ]
