# Generated by Django 5.0.3 on 2024-11-07 11:33

import django.db.models.deletion
import project.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('surnames', models.CharField(default='', max_length=50, verbose_name='surnames')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('email_verification_code', models.CharField(default='0000')),
                ('email_verified', models.BooleanField(default=False, help_text='Specifies whether the user has verified their email. You can only access the different sections of the application when you have verified it.', verbose_name='email verified')),
                ('is_janitor', models.BooleanField(blank=True, default=False, null=True, verbose_name='is janitor')),
                ('is_active', models.BooleanField(default=True, help_text='If the box is unchecked, the user will not be able to authenticate to access the application. It is usually only disabled when you want to unsubscribe a user but retaining their data.', verbose_name='is active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='is staff')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entities', to='entities.entity', verbose_name='Entity')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=(project.models.SetBooleanDatetimeMixin, models.Model),
        ),
    ]
