# Generated by Django 5.0.3 on 2025-03-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_data_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_janitor',
            field=models.BooleanField(default=False, verbose_name='is janitor'),
        ),
    ]
