# Generated by Django 5.0.3 on 2024-11-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_data_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=True, help_text='If the box is unchecked, its means that the user is from an external entity and its validation is pending.', verbose_name='is verified'),
        ),
    ]
