from datetime import time

START_TIME = time(8, 0)
START_TIME_PLUS_ONE = time(9, 0)
HALF_TIME = time(14, 0)
END_TIME = time(18, 0)
END_TIME_MINUS_ONE = time(17, 0)
# Discounts
GENERAL_DISCOUNT = 0
HOSTED_DISCOUNT = -0.4
BLOC4_DISCOUNT = -0.5
OUTSIDE_DISCOUNT = 0.15
