# Generated by Django 5.0.3 on 2024-11-07 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autonomous_community', models.SmallIntegerField(choices=[(1, 'Andalucia'), (2, 'Zaragoza'), (3, 'Asturias'), (4, 'Illes Balears'), (5, 'Santa Cruz de Tenerife'), (6, 'Cantàbria'), (7, 'Castilla y León'), (8, 'Castilla - La Mancha'), (9, 'Catalunya'), (10, 'País Valencià'), (11, 'Extremadura'), (12, 'Galícia'), (13, 'Madrid'), (14, 'Múrcia'), (15, 'Navarra'), (16, 'Euskal Herria'), (17, 'La Rioja'), (18, 'Ceuta'), (19, 'Melilla')], verbose_name='Autonomous Community')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'província',
                'verbose_name_plural': 'provincies',
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counties', to='provinces_towns.province', verbose_name='Province')),
            ],
            options={
                'verbose_name': 'comarca',
                'verbose_name_plural': 'comarques',
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='counties', to='provinces_towns.county', verbose_name='County')),
            ],
            options={
                'verbose_name': 'població',
                'verbose_name_plural': 'poblacions',
                'ordering': ['name'],
            },
        ),
    ]
