# Generated by Django 5.0.3 on 2024-06-19 08:34

import django.core.validators
import django.db.models.deletion
import project.fields.flowbite
import project.models
import project.storage_backends
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', project.fields.flowbite.ModelCharField(help_text='Name of the room', max_length=50, unique=True, verbose_name='Name')),
                ('location', project.fields.flowbite.ModelCharField(help_text='Room location', max_length=50, verbose_name='Location')),
                ('price', project.fields.flowbite.ModelFloatField(help_text='Hourly price', verbose_name='Price')),
                ('capacity', project.fields.flowbite.ModelIntegerField(help_text='Maximum seating capacity of the room', verbose_name='Capacity')),
                ('picture', project.fields.flowbite.ModelImageField(help_text='Photo of the room', storage=project.storage_backends.PrivateMediaStorage(), upload_to='', validators=[django.core.validators.validate_image_file_extension], verbose_name='Picture')),
                ('equipment', project.fields.flowbite.ModelCharField(help_text='Equipment available in the room', max_length=500, verbose_name='Equipment')),
                ('room_type', project.fields.flowbite.ModelCharField(choices=[('event_room', 'Event Room')], help_text='Room type', max_length=50, verbose_name='Room type')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'room',
                'verbose_name_plural': 'rooms',
                'ordering': ['name'],
            },
            bases=(project.models.SetBooleanDatetimeMixin, models.Model),
        ),
    ]
