version: "3.5"

networks:
  bloc4-network:
    name: bloc4-network

services:
  bloc4-app:
    restart: on-failure
    container_name: bloc4-app
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: development
    env_file: ./.env
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000 --reload --threads=10
    ports:
      - "1401:8000"
    volumes:
      - ../src:/srv
    depends_on:
      - bloc4-db
    networks:
      - bloc4-network

  bloc4-db:
    container_name: bloc4-db
    image: postgres:14
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ../dumps:/dumps
    networks:
      - bloc4-network
