# Generated by Django 5.0.3 on 2024-05-21 11:02

import django.db.models.deletion
import project.fields.flowbite
import project.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provinces_towns', '0002_load_fixtures'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', project.fields.flowbite.ModelEmailField(help_text='Email address', max_length=100, unique=True)),
                ('fiscal_name', project.fields.flowbite.ModelCharField(help_text='Fiscal name', max_length=50)),
                ('nif', project.fields.flowbite.ModelCharField(help_text='Tax identification number', max_length=9, unique=True, verbose_name='NIF')),
                ('postal_code', project.fields.flowbite.ModelIntegerField(help_text='Postal Code')),
                ('address', project.fields.flowbite.ModelCharField(help_text='Address', max_length=150)),
                ('country', project.fields.flowbite.ModelCharField(default='Spain', help_text='Country', max_length=50)),
                ('is_resident', project.fields.flowbite.ModelBooleanField(default=False, help_text='The entity has permanent premises in Bloc4')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('person_responsible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_responsible', to=settings.AUTH_USER_MODEL, verbose_name='person responsible')),
                ('town', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities', to='provinces_towns.town', verbose_name='Town')),
            ],
            options={
                'verbose_name': 'entity',
                'verbose_name_plural': 'entities',
                'ordering': ['fiscal_name'],
                'unique_together': {('id', 'person_responsible')},
            },
            bases=(project.models.SetBooleanDatetimeMixin, models.Model),
        ),
    ]
