# Generated by Django 5.0.3 on 2024-05-29 08:08

import project.fields.flowbite
import project.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('email', project.fields.flowbite.ModelEmailField(help_text='Email address', max_length=100, unique=True)),
                ('fiscal_name', project.fields.flowbite.ModelCharField(help_text='Fiscal name', max_length=50)),
                ('nif', project.fields.flowbite.ModelCharField(help_text='Tax identification number', max_length=9, unique=True, verbose_name='NIF')),
                ('postal_code', project.fields.flowbite.ModelCharField(help_text='Postal Code', max_length=5, verbose_name='Postal Code')),
                ('address', project.fields.flowbite.ModelCharField(help_text='Address', max_length=150)),
                ('country', project.fields.flowbite.ModelCharField(default='Spain', help_text='Country', max_length=50)),
                ('is_resident', project.fields.flowbite.ModelBooleanField(default=False, help_text='The entity has permanent premises in Bloc4')),
            ],
            options={
                'verbose_name': 'entity',
                'verbose_name_plural': 'entities',
                'ordering': ['fiscal_name'],
            },
            bases=(project.models.SetBooleanDatetimeMixin, models.Model),
        ),
    ]
