# Generated by Django 5.0.3 on 2024-11-27 15:13

import django.core.validators
import project.models
import project.storage_backends
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('entity_email', models.EmailField(max_length=100, unique=True, verbose_name='Email address')),
                ('fiscal_name', models.CharField(max_length=50, verbose_name='Fiscal name')),
                ('nif', models.CharField(help_text='Tax identification number', max_length=9, unique=True, verbose_name='NIF')),
                ('town', models.CharField(blank=True, default='', verbose_name='Town')),
                ('postal_code', models.CharField(max_length=5, verbose_name='Postal Code')),
                ('address', models.CharField(max_length=150, verbose_name='Address')),
                ('country', models.CharField(default='Spain', max_length=50, verbose_name='Country')),
                ('entity_type', models.CharField(choices=[('hosted', 'Hosted entity'), ('bloc4', 'Bloc4 entity'), ('general', 'Federated cooperative'), ('outside', 'Other entities')], default='general', max_length=20, verbose_name='Entity type')),
                ('reservation_privilege', models.BooleanField(default=False, help_text='Allows reservations without date restrictions', verbose_name='Reservation privilege')),
                ('logo', models.ImageField(blank=True, help_text='Logo of the entity', storage=project.storage_backends.PublicMediaStorage(), upload_to='', validators=[django.core.validators.validate_image_file_extension], verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'entity',
                'verbose_name_plural': 'entities',
                'ordering': ['fiscal_name'],
            },
            bases=(project.models.SetBooleanDatetimeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EntityPrivilege',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('monthly_hours_meeting', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='Free monthly hours for meeting rooms')),
                ('anual_hours_class', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='Free annual hours for classrooms')),
                ('class_reservation_privilege', models.BooleanField(default=False, help_text='Classrooms can be reserved without prior authorization', verbose_name='Classroom privilege')),
            ],
            options={
                'abstract': False,
            },
            bases=(project.models.SetBooleanDatetimeMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MonthlyBonus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('date', models.DateField(verbose_name='Date')),
                ('amount', models.FloatField(verbose_name='Amount')),
            ],
            options={
                'verbose_name': 'Monthly bonus',
                'verbose_name_plural': 'Monthly bonuses',
                'ordering': ['entity', 'date'],
            },
            bases=(project.models.SetBooleanDatetimeMixin, models.Model),
        ),
    ]
