# Generated by Django 5.0.3 on 2024-07-10 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
        ('provinces_towns', '0002_load_fixtures'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='entity',
            name='person_responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='person_responsible', to=settings.AUTH_USER_MODEL, verbose_name='person responsible'),
        ),
        migrations.AddField(
            model_name='entity',
            name='town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities', to='provinces_towns.town', verbose_name='Town'),
        ),
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together={('id', 'person_responsible')},
        ),
    ]
