# Generated by Django 5.0.3 on 2024-11-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_data_load_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.CharField(choices=[('general', 'Federated cooperative'), ('hosted', 'Hosted entity'), ('bloc4', 'Bloc4 entity'), ('outside', 'Other entities')], default='general', max_length=20, verbose_name='Entity type'),
        ),
    ]
