# Generated by Django 5.0.3 on 2025-03-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_data_load_entity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlybonus',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Amount'),
        ),
    ]
