# Generated by Django 5.0.3 on 2025-04-24 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_data_load_entity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.CharField(choices=[('hosted', 'Hosted entity'), ('bloc4', 'Bloc4 entity'), ('general', 'Public sector and social economy entities'), ('federated', 'Coòpolis and federated cooperatives'), ('outside', 'Other entities')], default='general', max_length=20, verbose_name='Entity type'),
        ),
        migrations.AlterField(
            model_name='entityprivilege',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='monthlybonus',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='monthlybonus',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
    ]
