# Generated by Django 5.0.3 on 2024-09-03 11:21

import project.fields.flowbite
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_data_load_entity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='is_resident',
        ),
        migrations.AddField(
            model_name='entity',
            name='entity_type',
            field=project.fields.flowbite.ModelSelectDropdownField(choices=[('general', 'General entity'), ('hosted', 'Hosted entity'), ('bloc4', 'Bloc4 entity'), ('outside', 'Entity outside the ESS and public sector')], default='general', max_length=20, verbose_name='Entity type'),
        ),
    ]
