# Generated by Django 5.0.3 on 2024-09-16 14:07

import project.fields.flowbite
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_remove_entity_is_resident_entity_entity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='reservation_privilege',
            field=project.fields.flowbite.ModelBooleanField(default=False, help_text='Allows reservations without date restrictions', verbose_name='Reservation privilege'),
        ),
    ]
