# Generated by Django 5.0.3 on 2024-11-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_alter_entity_entity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.CharField(choices=[('hosted', 'Hosted entity'), ('bloc4', 'Bloc4 entity'), ('general', 'Federated cooperative'), ('outside', 'Other entities')], default='general', max_length=20, verbose_name='Entity type'),
        ),
    ]
