# Generated by Django 5.0.3 on 2024-10-10 10:22

import django.core.validators
import project.fields.flowbite
import project.storage_backends
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_alter_entity_reservation_privilege'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='address',
            field=project.fields.flowbite.ModelCharField(max_length=150, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='country',
            field=project.fields.flowbite.ModelCharField(default='Spain', max_length=50, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='email',
            field=project.fields.flowbite.ModelEmailField(max_length=100, unique=True, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='fiscal_name',
            field=project.fields.flowbite.ModelCharField(max_length=50, verbose_name='Fiscal name'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='logo',
            field=project.fields.flowbite.ModelImageField(blank=True, help_text='Logo of the entity', null=True, storage=project.storage_backends.PublicMediaStorage(), upload_to='', validators=[django.core.validators.validate_image_file_extension], verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='postal_code',
            field=project.fields.flowbite.ModelCharField(max_length=5, verbose_name='Postal Code'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='town',
            field=project.fields.flowbite.ModelCharField(blank=True, null=True, verbose_name='Town'),
        ),
    ]
