# Generated by Django 5.0.3 on 2024-09-16 11:08

import django.core.validators
import project.fields.flowbite
import project.storage_backends
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_alter_entity_reservation_privilege'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='logo',
            field=project.fields.flowbite.ModelImageField(blank=True, help_text='Logo of the entity', null=True, storage=project.storage_backends.PublicMediaStorage(), upload_to='', validators=[django.core.validators.validate_image_file_extension], verbose_name='Logo'),
        ),
    ]
