# Generated by Django 5.0.3 on 2024-11-08 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_alter_entity_entity_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='email',
            new_name='entity_email',
        ),
    ]
