# Generated by Django 5.0.3 on 2024-09-12 13:41

import project.fields.flowbite
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_entity_reservation_privilege'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='reservation_privilege',
            field=project.fields.flowbite.ModelBooleanField(default=False, help_text='Allows reservations more than 30 days in advance', verbose_name='Reservation privilege'),
        ),
    ]
