# Generated by Django 5.0.3 on 2024-11-08 14:49

import django.db.models.deletion
import project.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_rename_email_entity_entity_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityPrivilege',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('monthly_hours_meeting', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Free monthly hours for meeting rooms')),
                ('anual_hours_class', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Free annual hours for classrooms')),
                ('class_reservation_privilege', models.BooleanField(default=False, help_text='Classrooms can be reserved without prior authorization', verbose_name='Classroom privilege')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entity_privilege', to='entities.entity')),
            ],
            options={
                'abstract': False,
            },
            bases=(project.models.SetBooleanDatetimeMixin, models.Model),
        ),
    ]
