# Generated by Django 5.0.3 on 2024-11-11 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0008_monthlybonus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlybonus',
            options={'ordering': ['entity', 'date'], 'verbose_name': 'Monthly bonus', 'verbose_name_plural': 'Monthly bonuses'},
        ),
    ]
