# Generated by Django 5.0.3 on 2024-11-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0009_alter_monthlybonus_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityprivilege',
            name='anual_hours_class',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='Free annual hours for classrooms'),
        ),
        migrations.AlterField(
            model_name='entityprivilege',
            name='monthly_hours_meeting',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='Free monthly hours for meeting rooms'),
        ),
    ]
