# Generated by Django 5.0.3 on 2024-12-10 15:18

import django.core.validators
import project.models
import project.storage_backends
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(default='', max_length=100, verbose_name='Title')),
                ('reservation_type', models.CharField(choices=[('hourly', 'Hourly reservation'), ('morning', 'Morning reservation'), ('afternoon', 'Afternoon reservation'), ('whole_day', 'Whole day reservation')], default='hourly', max_length=10, verbose_name='Choose the option that interests you most')),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.TimeField(verbose_name='Start time')),
                ('end_time', models.TimeField(verbose_name='End time')),
                ('assistants', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Assistants')),
                ('is_budgeted', models.BooleanField(default=False, verbose_name='Is budgeted?')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is paid?')),
                ('catering', models.BooleanField(blank=True, default=False, verbose_name='Do I need catering service?')),
                ('notes', models.TextField(default='', max_length=500, verbose_name='Do you need to tell us something?')),
                ('activity_type', models.CharField(choices=[('bloc4', 'Reservation for Bloc4BCN services'), ('ateneu', 'Activity within the work plan of the Ateneu Cooperatiu de Barcelona or Bloc4BCN agreement'), ('none', 'None of the two')], default='bloc4', max_length=10, verbose_name="Ateneu's activity")),
                ('bloc4_type', models.CharField(blank=True, choices=[('training', 'ESS continuous training'), ('accompaniment', 'Accompaniment'), ('financing', 'Access to financing'), ('techbloc4', 'TechBloc4-Digitalization'), ('acts', 'Acts and events'), ('internationalization', 'Internationalization'), ('attention_point', 'ESS attention point'), ('challenges', 'Challenges'), ('communication', 'Communication and disclosure'), ('intercooperation', 'Local intercooperation'), ('jovess', 'JovEES'), ('governance', 'Governance Spaces'), ('diagnosis', 'Diagnosis of ESS')], default='', max_length=20, verbose_name='Service type Bloc4BCN')),
                ('privacy', models.CharField(choices=[('private', 'Private training'), ('public', 'Public training')], default='private', help_text='Public events must be open to all citizens and will be published in the Bloc4BCN Agenda, subject to approval.', max_length=20, verbose_name='Type of event')),
                ('description', models.CharField(blank=True, help_text='This information will be used in the Bloc4BCN Agenda publication of this event.', max_length=500, verbose_name='Description')),
                ('poster', models.ImageField(blank=True, help_text='This information will be used in the Bloc4BCN Agenda publication of this event.', storage=project.storage_backends.PublicMediaStorage(), upload_to='', validators=[django.core.validators.validate_image_file_extension], verbose_name='Poster')),
                ('url', models.URLField(blank=True, default='', help_text='This information will be used in the Bloc4BCN Agenda publication of this event.', verbose_name='URL of the activity')),
                ('total_price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Total price')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='canceled_at')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('refused', 'Refused')], default='pending', help_text='Status of the reservation', max_length=20, verbose_name='status')),
            ],
            options={
                'verbose_name': 'reservation',
                'verbose_name_plural': 'reservations',
                'ordering': ['-date'],
            },
            bases=(project.models.SetBooleanDatetimeMixin, models.Model),
        ),
    ]
