# Generated by Django 5.0.3 on 2024-07-10 13:59

import project.fields.flowbite
import project.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.TimeField(help_text='Start time of the reservation', verbose_name='Start time')),
                ('end_time', models.TimeField(help_text='End time of the reservation', verbose_name='End time')),
                ('motivation', project.fields.flowbite.ModelCharField(blank=True, default='', help_text='Motivation for the reservation', max_length=500, null=True, verbose_name='Motivation')),
                ('assistants', project.fields.flowbite.ModelCharField(blank=True, default='', help_text='Assistants for the reservation', max_length=500, null=True, verbose_name='Assistants')),
                ('is_paid', project.fields.flowbite.ModelBooleanField(default=False, help_text='Is the reservation paid?', verbose_name='Is paid?')),
                ('total_price', project.fields.flowbite.ModelFloatField(blank=True, default=0, help_text='Total price of the reservation', null=True, verbose_name='Total price')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='canceled_at')),
                ('status', project.fields.flowbite.ModelSelectDropdownField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('refused', 'Refused')], default='pending', help_text='Status of the reservation', max_length=20, verbose_name='status')),
            ],
            options={
                'verbose_name': 'reservation',
                'verbose_name_plural': 'reservations',
                'ordering': ['-date'],
            },
            bases=(project.models.SetBooleanDatetimeMixin, models.Model),
        ),
    ]
