# Generated by Django 5.0.3 on 2025-03-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_data_emails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='total_price',
            new_name='base_price',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('refused', 'Refused')], default='pending', help_text='The Status can only be modified by using the buttons below.', max_length=20, verbose_name='status'),
        ),
    ]
