# Generated by Django 5.0.3 on 2025-04-24 13:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_data_emails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='total_price',
        ),
        migrations.AddField(
            model_name='reservation',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Total price'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='billed_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='billed at'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='billed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billed_reservations', to=settings.AUTH_USER_MODEL, verbose_name='billed by'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='checked_in',
            field=models.BooleanField(default=False, verbose_name='checked in'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_billed',
            field=models.BooleanField(default=False, verbose_name='billed'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='activity_type',
            field=models.CharField(choices=[('none', 'None of the two'), ('bloc4', 'Activity for Bloc4BCN services'), ('ateneu', 'Activity for the Ateneu Cooperatiu de Barcelona')], default='none', max_length=10, verbose_name='Does the activity belong to one of these services?'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('refused', 'Refused')], default='pending', help_text='The Status can only be modified by using the buttons below.', max_length=20, verbose_name='status'),
        ),
    ]
