# Generated by Django 5.0.3 on 2024-07-31 14:51

import project.fields.flowbite
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_data_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='assistants',
            field=project.fields.flowbite.ModelIntegerField(blank=True, default='', help_text='Assistants for the reservation', null=True, verbose_name='Assistants'),
        ),
    ]
