# Generated by Django 5.0.3 on 2024-11-08 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_data_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='assistants',
            field=models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Assistants'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='description',
            field=models.CharField(blank=True, help_text='Description for the activity', max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Is paid?'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Title'),
        ),
    ]
