# Generated by Django 5.0.3 on 2025-03-24 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_data_emails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='total_price',
        ),
        migrations.AddField(
            model_name='reservation',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Total price'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='checked_in',
            field=models.BooleanField(default=False, verbose_name='Checked in'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('refused', 'Refused')], default='pending', help_text='The Status can only be modified by using the buttons below.', max_length=20, verbose_name='status'),
        ),
    ]
