# Generated by Django 5.0.3 on 2025-03-21 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_rename_total_price_reservation_base_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Total price'),
        ),
    ]
