# Generated by Django 5.0.3 on 2025-04-07 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_remove_reservation_total_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='billed_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billed_reservations', to=settings.AUTH_USER_MODEL, verbose_name='billed by'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_billed',
            field=models.DateTimeField(editable=False, null=True, verbose_name='billed at'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='is_billed',
            field=models.BooleanField(default=False, verbose_name='billed'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='checked_in',
            field=models.BooleanField(default=False, verbose_name='checked in'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_related', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
    ]
