# Generated by Django 5.0.3 on 2024-08-26 11:50

import project.fields.flowbite
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_reservation_assistants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='assistants',
            field=project.fields.flowbite.ModelIntegerField(blank=True, default=1, help_text='Assistants for the reservation', null=True, verbose_name='Assistants'),
        ),
    ]
