# Generated by Django 5.0.3 on 2024-11-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_reservation_assistants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_type',
            field=models.CharField(choices=[('hourly', 'Hourly reservation'), ('morning', 'Morning reservation'), ('afternoon', 'Afternoon reservation'), ('whole_day', 'Whole day reservation')], default='hourly', help_text='Only hourly reservations are available for hourly bonuses', max_length=10, verbose_name='Reservation type'),
        ),
    ]
