# Generated by Django 5.0.3 on 2025-03-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='checked_in',
            field=models.BooleanField(default=False, verbose_name='checked_in'),
        ),
    ]
