# Generated by Django 5.0.3 on 2024-08-30 14:33

import django.core.validators
import project.fields.flowbite
import project.storage_backends
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_alter_reservation_assistants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='motivation',
        ),
        migrations.AddField(
            model_name='reservation',
            name='bloc4_reservation',
            field=project.fields.flowbite.ModelBooleanField(default=False, help_text='Reservation for Bloc4 services', verbose_name='Bloc4 services'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='catering',
            field=project.fields.flowbite.ModelBooleanField(default=False, verbose_name='Do I need catering service?'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='description',
            field=project.fields.flowbite.ModelCharField(default='', help_text='Description for the reservation', max_length=500, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='notes',
            field=project.fields.flowbite.ModelCharField(default='', help_text='Notes for the reservation', max_length=500, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='poster',
            field=project.fields.flowbite.ModelImageField(blank=True, null=True, storage=project.storage_backends.PublicMediaStorage(), upload_to='', validators=[django.core.validators.validate_image_file_extension], verbose_name='Poster'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='privacy',
            field=project.fields.flowbite.ModelSelectDropdownField(choices=[('public', 'Public training'), ('private', 'Private training')], default='public', help_text='Privacy of the reservation', max_length=20, verbose_name='privacy'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='title',
            field=project.fields.flowbite.ModelCharField(blank=True, default='', help_text='Title for the reservation', max_length=100, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='url',
            field=project.fields.flowbite.ModelUrlField(default='', verbose_name='URL of the activity'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='assistants',
            field=project.fields.flowbite.ModelIntegerField(default=1, help_text='Assistants for the reservation', verbose_name='Assistants'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_price',
            field=project.fields.flowbite.ModelFloatField(default=0, help_text='Total price of the reservation', null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Total price'),
        ),
    ]
