# Generated by Django 5.0.3 on 2025-04-07 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_reservation_billed_by_reservation_date_billed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='date_billed',
            new_name='billed_at',
        ),
    ]
