# Generated by Django 5.0.3 on 2024-11-14 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_reservation_reservation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='bloc4_reservation',
            field=models.BooleanField(default=False, verbose_name='Reservation for Bloc4BCN services'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_price',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Total price'),
        ),
    ]
