# Generated by Django 5.0.3 on 2024-08-30 14:52

import project.fields.flowbite
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_remove_reservation_motivation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='bloc4_reservation',
            field=project.fields.flowbite.ModelBooleanField(default=False, verbose_name='Reservation for Bloc4 services'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='description',
            field=project.fields.flowbite.ModelCharField(blank=True, default='', help_text='Description for the reservation', max_length=500, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='privacy',
            field=project.fields.flowbite.ModelSelectDropdownField(choices=[('public', 'Public training'), ('private', 'Private training')], default='public', help_text='If the training is public, it will appear in the bloc4 agenda', max_length=20, verbose_name='privacy'),
        ),
    ]
