# Generated by Django 5.0.3 on 2024-11-21 14:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_reservation_bloc4_reservation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='assistants',
            field=models.IntegerField(default='', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Assistants'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='catering',
            field=models.BooleanField(blank=True, default=False, verbose_name='Do I need catering service?'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='notes',
            field=models.CharField(default='', max_length=500, verbose_name='Notes'),
        ),
    ]
