# Generated by Django 5.0.3 on 2024-11-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_reservation_bloc4_reservation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='notes',
            field=models.CharField(default='', max_length=500, verbose_name='Do you need to tell us something?'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='privacy',
            field=models.CharField(choices=[('private', 'Private training'), ('public', 'Public training')], default='private', help_text='Public events must be open to all citizens and will be published in the Bloc4BCN Agenda, subject to approval.', max_length=20, verbose_name='Type of event'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_type',
            field=models.CharField(choices=[('hourly', 'Hourly reservation'), ('morning', 'Morning reservation'), ('afternoon', 'Afternoon reservation'), ('whole_day', 'Whole day reservation')], default='hourly', help_text='Only hourly reservations are available for hourly bonuses', max_length=10, verbose_name='Choose the option that interests you most'),
        ),
    ]
