# Generated by Django 5.0.3 on 2024-08-30 15:01

import project.fields.flowbite
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_alter_reservation_bloc4_reservation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='url',
            field=project.fields.flowbite.ModelUrlField(blank=True, default='', verbose_name='URL of the activity'),
        ),
    ]
