# Generated by Django 5.0.3 on 2024-11-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_alter_reservation_notes_alter_reservation_privacy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='bloc4_reservation',
        ),
        migrations.AddField(
            model_name='reservation',
            name='activity_type',
            field=models.CharField(choices=[('bloc4', 'Reservation for Bloc4BCN services'), ('ateneu', 'Activity within the work plan of the Ateneu Cooperatiu de Barcelona or Bloc4BCN agreement.'), ('none', 'None of the two')], default='bloc4', max_length=10, verbose_name="Ateneu's activity"),
        ),
        migrations.AddField(
            model_name='reservation',
            name='bloc4_type',
            field=models.CharField(choices=[('training', 'ESS continuous training'), ('accompaniment', 'Accompaniment'), ('financing', 'Access to financing'), ('techbloc4', 'TechBloc4-Digitalization'), ('acts', 'Acts and events'), ('internationalization', 'Internationalization'), ('attention_point', 'ESS attention point'), ('challenges', 'Challenges'), ('communication', 'Communication and disclosure'), ('intercooperation', 'Local intercooperation'), ('jovess', 'JovEES'), ('governance', 'Governance Spaces'), ('diagnosis', 'Diagnosis of ESS')], default='training', max_length=20, verbose_name='Service type Bloc4BCN'),
        ),
    ]
