# Generated by Django 5.0.3 on 2024-08-30 15:03

import project.fields.flowbite
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_alter_reservation_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='url',
            field=project.fields.flowbite.ModelUrlField(blank=True, default='', null=True, verbose_name='URL of the activity'),
        ),
    ]
