# Generated by Django 5.0.3 on 2024-11-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_remove_reservation_bloc4_reservation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='activity_type',
            field=models.CharField(choices=[('bloc4', 'Reservation for Bloc4BCN services'), ('ateneu', 'Activity within the work plan of the Ateneu Cooperatiu de Barcelona or Bloc4BCN agreement'), ('none', 'None of the two')], default='bloc4', max_length=10, verbose_name="Ateneu's activity"),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='bloc4_type',
            field=models.CharField(blank=True, choices=[('training', 'ESS continuous training'), ('accompaniment', 'Accompaniment'), ('financing', 'Access to financing'), ('techbloc4', 'TechBloc4-Digitalization'), ('acts', 'Acts and events'), ('internationalization', 'Internationalization'), ('attention_point', 'ESS attention point'), ('challenges', 'Challenges'), ('communication', 'Communication and disclosure'), ('intercooperation', 'Local intercooperation'), ('jovess', 'JovEES'), ('governance', 'Governance Spaces'), ('diagnosis', 'Diagnosis of ESS')], default='', max_length=20, verbose_name='Service type Bloc4BCN'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='notes',
            field=models.TextField(default='', max_length=500, verbose_name='Do you need to tell us something?'),
        ),
    ]
