# Generated by Django 5.0.3 on 2024-11-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_alter_reservation_activity_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_budgeted',
            field=models.BooleanField(default=False, verbose_name='Is budgeted?'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_type',
            field=models.CharField(choices=[('hourly', 'Hourly reservation'), ('morning', 'Morning reservation'), ('afternoon', 'Afternoon reservation'), ('whole_day', 'Whole day reservation')], default='hourly', max_length=10, verbose_name='Choose the option that interests you most'),
        ),
    ]
