# Generated by Django 5.0.3 on 2024-09-02 15:14

import project.fields.flowbite
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_alter_reservation_assistants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='title',
            field=project.fields.flowbite.ModelCharField(default='', help_text='Title for the reservation', max_length=100, verbose_name='Title'),
        ),
    ]
