# Generated by Django 5.0.3 on 2024-11-22 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_alter_reservation_assistants_and_more'),
        ('reservations', '0010_reservation_is_budgeted_and_more'),
    ]

    operations = [
    ]
