# Generated by Django 5.0.3 on 2024-09-02 16:46

import django.core.validators
import project.fields.flowbite
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_alter_reservation_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='total_price',
            field=project.fields.flowbite.ModelFloatField(default=0, help_text='Total price will be calculated on save.', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Total price'),
        ),
    ]
