# Generated by Django 5.0.3 on 2024-11-27 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_merge_20241122_1649'),
        ('rooms', '0003_alter_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end_time',
            field=models.TimeField(verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='notes',
            field=models.TextField(default='', max_length=500, verbose_name='Do you need to tell us something?'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(help_text='If you want to change the room and notify the user, first, change the room, save and then click the button to notify.', on_delete=django.db.models.deletion.CASCADE, related_name='reservation_room', to='rooms.room', verbose_name='room'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_time',
            field=models.TimeField(verbose_name='Start time'),
        ),
    ]
