# Generated by Django 5.0.3 on 2024-09-03 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_alter_reservation_privacy'),
        ('reservations', '0012_alter_reservation_total_price'),
    ]

    operations = [
    ]
