# Generated by Django 5.0.3 on 2024-09-05 10:36

import django.core.validators
import project.fields.flowbite
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_merge_20240903_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='assistants',
            field=project.fields.flowbite.ModelIntegerField(default='', help_text='Assistants for the reservation', validators=[django.core.validators.MinValueValidator(2)], verbose_name='Assistants'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='privacy',
            field=project.fields.flowbite.ModelSelectDropdownField(choices=[('private', 'Private training'), ('public', 'Public training')], default='private', help_text='If the training is public, it will appear in the bloc4 agenda', max_length=20, verbose_name='privacy'),
        ),
    ]
