# Generated by Django 5.0.3 on 2024-09-12 13:41

import project.fields.flowbite
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_alter_reservation_assistants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='description',
            field=project.fields.flowbite.ModelCharField(blank=True, help_text='Description for the reservation', max_length=500, null=True, verbose_name='Description'),
        ),
    ]
